## Random Forest


```{r, echo=FALSE, results="hide"}
library(tidyverse)
library(magrittr)
library(keras)
library(arrow)
library(pbmcapply)
library(ranger)
library(caret)
Rcpp::sourceCpp('src/calc_payoff_per_title.cpp')
source("R/03-analysis.R")

Rcpp::sourceCpp('src/find_best_buy_sell_ind.cpp')
Rcpp::sourceCpp('src/find_best_buy_sell_dep.cpp')

data_wide_10 <- arrow::read_feather("data/steps/data_wide_10.feather")
  
set.seed(123456)
train_idx <- sample(x = nrow(data_wide_10), size = floor(0.8 * nrow(data_wide_10)))
test_idx <- setdiff(seq_len(nrow(data_wide_10)), train_idx)
both_first <- c("buy", "sell")[sample(c(1, 2), nrow(data_wide_10), replace = TRUE)]

sample_idx <- seq_len(500)

```

```{r}

data_wide_3_Low <- select(data_wide_10, c("Date", levels(interaction(c("Open_", "Low_", "High_", "Close_"), 1:3, sep="")), "Open_0", "Low_0"))[train_idx, ] %>%
  mutate(Low_0 = factor(Low_0))

rf_fit <- train(Low_0 ~ ., 
                data = data_wide_3_Low, 
                method = "ranger")

```