---
title: "Die Bestimmung optimaler Kauf- und Verkaufspreise von Basiswerten zur Wahrung der täglichen Delta-Neutralität beim Handel von Aktienoptionen mit Hilfe verschiedener Machine Learning Methoden"
author: 
  - Fabian Gehring, Sattelbogenstrasse 31, 5610 Wohlen
  - Betreut durch Dr. Thomas Oskar Weinmann, ZHAW
site: bookdown::bookdown_site
documentclass: scrartcl
bibliography: ["mas.bib"]
biblio-style: apalike
link-citations: yes
header-includes:
  - \usepackage[ngerman]{babel}
  - \usepackage{float}
#  - \floatplacement{figure}{H} 

---


```{r setup_index, include = FALSE}
packages <- c(
  "bookdown",
  "dplyr",
  "here",
  "jsonlite",
  "magrittr",
  "purrr",
  "quantmod",
  "qrmtools",
  "renv",
  "roxygen2",
  "stringr",
  "tibble"
)

# load packages
suppressMessages({
  for (pkg in packages) {
    library(pkg, character.only = TRUE)
  }
})

# load sources
for (file in list.files(here("R"), full.names = TRUE)) source(file)
```

\newpage
\section*{Selbständigkeitserklärung}

Mit der Abgabe dieser Arbeit versichert der/die Studierende, dass er/sie die Arbeit selbständig und ohne fremde Hilfe verfasst hat. (Bei Teamarbeiten gelten die Leistungen der übrigen Teammitglieder nicht als fremde Hilfe).

Der/die unterzeichnende Studierende erklärt, dass alle zitierten Quellen (auch Internetseiten) im Text oder Anhang korrekt nachgewiesen sind, d.h. dass die vorliegende Arbeit keine Plagiate enthält, also keine Teile, die teilweise oder vollständig aus einem fremden Text oder einer fremden Arbeit unter Vorgabe der eigenen Urheberschaft bzw. ohne Quellenangabe übernommen worden sind.
\vspace*{0.4cm}

Wohlen, 29.06.2020  
Fabian Gehring


\newpage

# Management Summary {-#summary}

In vorliegender Arbeit wird untersucht, ob mit Hilfe maschineller Lernalgorithmen Kauf- und Verkaufspreise von Aktien so prognostiziert werden können, dass der Ausgleich von aufgelaufenem Delta bei Optionspositionen mit höherem Payoff erfolgen kann als mit einfacheren Strategien. Es gilt dabei die Nebenbedingung, dass die Position zum Tagesende bezüglich Preisschwankungen abgesichert sein muss. Als Referenz dient dabei die Strategie, bei welcher untertags kein Kauf- und Verkauf von Aktien erfolgt, sondern der Ausgleich des Deltas komplett zum Tagesschlusskurs erfolgt.
Als Datenbasis dienen die historischen Eröffnungs-, Tiefst-, Höchst- und Schlusskurse von rund 1'600 grossen kotierten Unternehmungen weltweit. 

In einem ersten Ansatz werden die Kauf- und Verkaufsschranken als symmetrische Auslenkungen vom jeweiligen Eröffnungskurs gesetzt. Der Payoff der Referenzstrategie lässt sich so um rund 8% übertreffen. Es zeigt sich dabei, dass die Volatilität der vergangenen 10 Tage einen erklärenden Einfluss auf die Höhe der optimalen Auslenkung hat. Die Überperformance lässt sich durch Aufteilung der Daten in Tief- und Hochvolatilitätsumfeld auf beinahe 10% steigern.

Der zweite Ansatz basiert auf der Suche ähnlicher Kursverläufe in der Vergangenheit mittels K-Nearest-Neigbor Verfahren. Die Überperformance dieses Ansatzes liegt bei ebenfalls rund 8%. Die Analyse zeigt ferner, dass die Güte des Modelles mit steigender Anzahl Vergleichskurse zunimmt. Stehen genügend Vergleichskurse zur Verfügung, kann eine Sättigung des Lerneffekts beobachtet werden.

Im dritten Ansatz werden die Kauf- und Verkaufsschranken mittels neuronaler Netze vorhergesagt. Als einzige der untersuchten Methoden wird mit diesem Verfahren auch die Verteilung der prognostizierten Preise miteinbezogen. Es resultieren Überschussrenditen bis 15% im Vergleich zur Referenzstrategie. Dabei zeigt sich, dass sowohl mit der Modellierung ordinaler Preisklassen als auch mit der Modellierung voneinander abhängiger Innertagspreise bessere Ergebnisse erzielt werden können, als bei der Modellierung voneinander unabhängiger Preise.

